[package]
name = "paras-claim-rewards-contract"
version = "0.1.0"
authors = ["Paras"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "*", features = ["derive"] }
serde_json = "*"
near-sdk = "3.1.0"
near-contract-standards = "3.1.0"
